USE arquitectura;
INSERT INTO env1part1 (TIPO,	SUBTIPO,	 NOMBRE, 	TRANSMITANCIA)
VALUES
("VENTANA","Tipo de vidrio/policarbonato","vidrio simple incoloro (8 mm)","5.60"),
("VENTANA","Tipo de vidrio/policarbonato","vidrio simple incoloro (6 mm)","5.70"),
("VENTANA","Tipo de vidrio/policarbonato","vidrio simple incoloro (10 mm)","5.60"),
("VENTANA","Tipo de vidrio/policarbonato","vidrio laminado incoloro (4+4)","5.60"),
("VENTANA","Tipo de vidrio/policarbonato","vidrio laminado incoloro (6+6)","5.40"),
("VENTANA","Tipo de vidrio/policarbonato","vidrio laminado incoloro (8+8)","5.40"),
("VENTANA","Tipo de vidrio/policarbonato","vidrio insulado incoloro (4-6)","3.30"),
("VENTANA","Tipo de vidrio/policarbonato","vidrio insulado incoloro (4-9)","3.00"),
("VENTANA","Tipo de vidrio/policarbonato","vidrio insulado incoloro (4-12)","2.80"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (alveolar Estándar de 4 mm)","3.90"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (alveolar Estándar de 6 mm)","3.60"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (alveolar Estándar de 8 mm)","3.30"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (alveolar Estándar de 10 mm)","3.00"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (alveolar Estándar de 16 mm)","2.30"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (tipo Polygal Polyshade de 6 mm)","3.60"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (tipo Polygal Polyshade de 8 mm)","3.30"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (tipo Polygal Polyshade de 10 mm)","3.00"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (tipo Polygal Thermogal de 25 mm)","1.70"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (tipo Polygal Thermogal de 32 mm)","1.40"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (tipo Polygal Thermogal de 40 mm)","1.10"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (tipo Polygal Selectogal de 10 mm)","2.50"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (tipo Polygal Rainbow de 8 mm)","3.30"),
("VENTANA","Tipo de vidrio/policarbonato","policarbonato (tipo Polygal Selectogal de 16 mm)","2.20"),
("VENTANA","Tipo de carpintería del marco de ventana","Madera (densidad media alta: 700 kg/m3)","2.2"),
("VENTANA","Tipo de carpintería del marco de ventana","Madera (densidad media baja: 500 kg/m3)","2.0"),
("VENTANA","Tipo de carpintería del marco de ventana","Metálico (normal)","5.7"),
("VENTANA","Tipo de carpintería del marco de ventana","Metálico (con rotura de puente térmico entre 4 y 12 mm)","4.0"),
("VENTANA","Tipo de carpintería del marco de ventana","Metálico (con rotura de puente térmico > 12 mm)","3.2"),
("VENTANA","Tipo de carpintería del marco de ventana","PVC (dos cámaras)","2.2"),
("VENTANA","Tipo de carpintería del marco de ventana","PVC (tres cámaras)","1.8"),
("PUERTA","Tipo de puerta","Madera (hoja contraplacada de fibra MDF, espesor: 4 cm)","4.7"),
("PUERTA","Tipo de puerta","Madera (hoja maciza de madera, cualquier espesor)","3.5"),
("PUERTA","Tipo de puerta","Madera (hoja de vidrio simple en < 30% de la superficie de la hoja de madera maciza)","4.0"),
("PUERTA","Tipo de puerta","Madera (hoja de vidrio simple en 30% a 60% de la superficie de la hoja de madera maciza)","4.5"),
("PUERTA","Tipo de puerta","Madera (hoja de vidrio doble)","3.3"),
("PUERTA","Tipo de puerta","Metálico (hoja de metal)","5.8"),
("PUERTA","Tipo de puerta","Metálico (puerta cortafuego de una hoja (cualquier espesor)","3.0"),
("PUERTA","Tipo de puerta","Metálico (puerta cortafuego de dos hojas, espesor: 83 mm)","1.9"),
("PUERTA","Tipo de puerta","Metálico (hoja de vidrio simple)","5.8"),
("PUERTA","Tipo de puerta","Metálico (hoja de vidrio doble, con cámara de aire de 6 mm en < 30% de su superficie)","5.5"),
("PUERTA","Tipo de puerta","Metálico (hoja de vidrio doble, con cámara de aire de 6 mm en 30% a 70% de su superficie)","4.8"),
("PUERTA","Tipo de puerta","Metálico (hoja de vidrio doble, al 100%)","2.8"),
("PUERTA","Tipo de puerta","Hoja de vidrio (sin carpintería)","5.8");                                                             
