USE arquitectura;
INSERT INTO vidrios (NOMBRE,TRANSMITANCIA)
VALUES
('vidrio simple incoloro (8 mm)','5.60'),
('vidrio simple incoloro (6 mm)','5.70'),
('vidrio simple incoloro (10 mm)','5.60'),
('vidrio laminado incoloro (4+4)','5.60'),
('vidrio laminado incoloro (6+6)','5.40'),
('vidrio laminado incoloro (8+8)','5.40'),
('vidrio insulado incoloro (4-6)','3.30'),
('vidrio insulado incoloro (4-9)','3.00'),
('vidrio insulado incoloro (4-12)','2.80'),
('policarbonato (alveolar Estándar de 4 mm)','3.90'),
('policarbonato (alveolar Estándar de 6 mm)','3.60'),
('policarbonato (alveolar Estándar de 8 mm)','3.30'),
('policarbonato (alveolar Estándar de 10 mm)','3.00'),
('policarbonato (alveolar Estándar de 16 mm)','2.30'),
('policarbonato (tipo Polygal Polyshade de 6 mm)','3.60'),
('policarbonato (tipo Polygal Polyshade de 8 mm)','3.30'),
('policarbonato (tipo Polygal Polyshade de 10 mm)','3.00'),
('policarbonato (tipo Polygal Thermogal de 25 mm)','1.70'),
('policarbonato (tipo Polygal Thermogal de 32 mm)','1.40'),
('policarbonato (tipo Polygal Thermogal de 40 mm)','1.10'),
('policarbonato (tipo Polygal Selectogal de 10 mm)','2.50'),
('policarbonato (tipo Polygal Rainbow de 8 mm)','3.30'),
('policarbonato (tipo Polygal Selectogal de 16 mm)','2.20'),
('Madera (densidad media alta: 700 kg/m3)','2.2'),
('Madera (densidad media baja: 500 kg/m3)','2.0'),
('Metálico (normal)','5.7'),
('Metálico (con rotura de puente térmico entre 4 y 12 mm)','4.0'),
('Metálico (con rotura de puente térmico > 12 mm)','3.2'),
('PVC (dos cámaras)','2.2'),
('PVC (tres cámaras)','1.8'),
('Madera (hoja contraplacada de fibra MDF, espesor: 4 cm)','4.7'),
('Madera (hoja maciza de madera, cualquier espesor)','3.5'),
('Madera (hoja de vidrio simple en < 30% de la superficie de la hoja de madera maciza)','4.0'),
('Madera (hoja de vidrio simple en 30% a 60% de la superficie de la hoja de madera maciza)','4.5'),
('Madera (hoja de vidrio doble)','3.3'),
('Metálico (hoja de metal)','5.8'),
('Metálico (puerta cortafuego de una hoja (cualquier espesor)','3.0'),
('Metálico (puerta cortafuego de dos hojas, espesor: 83 mm)','1.9'),
('Metálico (hoja de vidrio simple)','5.8'),
('Metálico (hoja de vidrio doble, con cámara de aire de 6 mm en < 30% de su superficie)','5.5'),
('Metálico (hoja de vidrio doble, con cámara de aire de 6 mm en 30% a 70% de su superficie)','4.8'),
('Metálico (hoja de vidrio doble, al 100%)','2.8'),
('Hoja de vidrio (sin carpintería)','5.8');                                                             
