--using debpsfm7k9ccrj
INSERT INTO materiales (NOMBRE,COEFICIENTE)
VALUES
('Concreto (armado)','1.63'),
('Concreto (Cemento pulido, pisos de 5 cm. de espesor)','0.53'),
('Concreto (simple)','1.51'),
('Madera (Balsa)','0.06'),
('Madera (Conífera de densidad media: Pino insigne)','0.15'),
('Madera (Conífera densa: Pino Oregón, Ciprés)','0.18'),
('Madera (Conífera livianas: Cedro)','0.13'),
('Madera (Conífera muy densa)','0.23'),
('Madera (de densidad media: Abedul, Canelo, etc)','0.18'),
('Madera (densa: Capirona, Estoraque)','0.23'),
('Madera (liviana: Álamo, Avellano, etc)','0.14'),
('Madera (Machihembrada o traslapada, tornillo)','0.12'),
('Madera (muy densa: Algarrobo, Eucalipto)','0.29'),
('Madera (Puerta de madera)','0.12'),
('Madera (Triplay)','0.14'),
('Madera peruana (Cachimbo)','0.18'),
('Madera peruana (Catahua amarilla)','0.09'),
('Madera peruana (Ishpingo)','0.15'),
('Madera peruana (Quinilla colorada)','0.19'),
('Mampostería (Adobe)','0.90'),
('Mampostería (Bloque de arcilla - Ladrillo corriente)','0.84'),
('Mampostería (Bloque de arcilla - Ladrillo hueco de techo)','0.35'),
('Mampostería (Bloque de arcilla - Ladrillo pandereta)','0.44'),
('Mampostería (Bloque de arcilla - Ladrillo pastelero)','0.71'),
('Mampostería (Bloque de arcilla - Ladrillo tipo King Kong)','0.47'),
('Mampostería (Bloque de concreto - Unidad hueca)','0.50'),
('Material aislante (Aire)','0.03'),
('Material aislante (Corcho)','0.05'),
('Material aislante (Espuma de polietileno con aluminio  10 mm)','0.04'),
('Material aislante (Espuma de polietileno con aluminio  5 mm)','0.05'),
('Material aislante (Espuma elastomerica flexible)','0.05'),
('Material aislante (Fibra de vidrio)','0.04'),
('Material aislante (Fieltro)','0.05'),
('Material aislante (Lana de vidrio con foil)','0.04'),
('Material aislante (Lana de vidrio, alta densidad)','0.03'),
('Material aislante (Lana de vidrio, baja densidad)','0.04'),
('Material aislante (Lana de vidrio, media densidad)','0.04'),
('Material aislante (Lana mineral (baja densidad)','0.04'),
('Material aislante (Lana mineral)','0.04'),
('Material aislante (Lana mineral, alta densidad)','0.04'),
('Material aislante (Lana mineral, media densidad)','0.04'),
('Material aislante (Poliestireno expandido -EPS)','0.03'),
('Material aislante (Poliestireno extruido -XPS)','0.04'),
('Materiales varios (Acrilico)','0.20'),
('Materiales varios (Agua)','0.58'),
('Materiales varios (Asfalto)','0.70'),
('Materiales varios (Caucho natural)','0.13'),
('Materiales varios (Cloruro de polivinilo -PVC)','0.17'),
('Materiales varios (Hielo)','2.03'),
('Materiales varios (Linóleo)','0.17'),
('Materiales varios (Membrana asfáltica)','0.17'),
('Materiales varios (Neoprene)','0.23'),
('Materiales varios (Nieve)','0.30'),
('Materiales varios (Paja, cama de 2 cm)','0.09'),
('Materiales varios (Papel)','0.18'),
('Materiales varios (Policarbonato-PC)','0.20'),
('Materiales varios (Polietileno de alta densidad -HDPE)','0.50'),
('Materiales varios (Polietileno de alta densidad -LDPE)','0.33'),
('Materiales varios (Polipropileno -PP)','0.22'),
('Materiales varios (Resina epóxica)','0.20'),
('Materiales varios (Silicona)','0.35'),
('Materiales varios (Techo verde, 14 cm espesor)','0.17'),
('Materiales varios (Tela yute)','0.06'),
('Metal (Acero inoxidable)','15.6'),
('Metal (Acero)','50.0'),
('Metal (Aluminio)','230.0'),
('Metal (Bronce)','65.0'),
('Metal (Calamina metálica de 2 mm)','237.0'),
('Metal (Cobre)','380.0'),
('Metal (Estaño)','66.6'),
('Metal (Latón)','120.0'),
('Metal (Plomo)','35.0'),
('Metal (Zinc)','110.0'),
('Mortero (Cemento y cal o yeso)','0.87'),
('Mortero (Cemento-arena)','1.40'),
('Mortero (Enlucido de yeso)','0.40'),
('Panel (de corcho)','0.04'),
('Panel (de fibra de vidrio)','0.04'),
('Panel (de lana mineral)','0.04'),
('Panel (de yeso)','0.25'),
('Panel (fibrocemento)','0.23'),
('Panel (metálico aislante 100 mm de muro)','0.20'),
('Panel (metálico aislante 120 mm muro)','0.17'),
('Panel (metálico aislante 150 mm muro)','0.13'),
('Panel (metálico aislante 20 mm, techos autoportantes)','1.00'),
('Panel (metálico aislante 25 mm, techos autoportantes)','0.80'),
('Panel (metálico aislante 35 mm, techos autoportantes)','0.57'),
('Panel (metálico aislante 45 mm, techos autoportantes)','0.44'),
('Panel (metálico aislante 50 mm de muro)','0.40'),
('Panel (metálico aislante 60 mm de muro)','0.33'),
('Panel (metálico aislante 80 mm de muro)','0.25'),
('Revestimiento homogéneo (Alfombra de materiales sintéticos)','0.06'),
('Revestimiento homogéneo (Baldosa cerámica)','1.00'),
('Revestimiento homogéneo (Teja cerámica-porcelana)','1.30'),
('Revestimiento homogéneo (Teja de arcilla)','1.00'),
('Roca íngea (Basalto)','3.50'),
('Roca íngea (Granito)','2.80'),
('Roca íngea (Piedra pómez)','0.12'),
('Roca íngea (Roca natural porosa; por ej. lava)','0.55'),
('Roca metamórfica (Mármol)','3.50'),
('Roca metamórfica (Pizarra)','2.20'),
('Roca o suelo sedimentario (Arcilla o limo)','1.50'),
('Roca o suelo sedimentario (Arcilla refractaria)','0.46'),
('Roca o suelo sedimentario (Caliza media dura)','1.40'),
('Roca o suelo sedimentario (Caliza muy blanda)','0.85'),
('Roca o suelo sedimentario (Caliza muy dura)','2.30'),
('Roca o suelo sedimentario (Gravas y arenas: arena fina, arena gruesa, etc.)','2.00'),
('Roca o suelo sedimentario (Piedra canto rodado de 10 cm)','3.50'),
('Tablero de fibras (incluyendo MDF y MDP, media densidad)','0.18'),
('Tablero de fibras (incluyendo MDF y Trupan, baja densidad)','0.14'),
('Tablero de fibras (incluyendo MDF, alta densidad)','0.20'),
('Tablero de particulas (alta densidad, Melamina)','0.18'),
('Tablero de particulas (baja densidad)','0.13'),
('Tablero de particulas (mediana densidad)','0.15'),
('Tablero de virutas (tipo OSB)','0.13'),
('Tierra (Barro con paja de 2 cm)','0.09'),
('Tierra (Tierra)','0.52'),
('Tierra (Yeso)','0.30');